services:
  session_postgres:
    image: postgres:16
    container_name: session_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  discovery:
    build:
      context: .
      dockerfile: discovery/Dockerfile
    container_name: discovery
    ports:
      - "8761:8761"
  session:
    build:
      context: .
      dockerfile: session/Dockerfile
    container_name: session
    ports:
      - "8081:8081"
    depends_on:
      - session_postgres
      - discovery

volumes:
  pgdata:
  service_pgdata:
  kafka_data:
  zookeeper_data:
  zookeeper_log: