server.port=8082

jwt.public-key.path=keys/public.pem

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=myuser
spring.datasource.password=mypassword

spring.datasource.url=jdbc:postgresql://localhost:5438/mydatabase

twilio.auth_token=1d5ce576379ddc8f7cc1fa79359c037d
twilio.sender.phone_number=+16402463511
twilio.sid=AC71a114643fce3ea56b35ad90b70d2f4b
