server.port=8082

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=myuser
spring.datasource.password=mypassword

spring.datasource.url=jdbc:postgresql://localhost:5438/mydatabase

twilio.auth_token=
twilio.sender.phone_number=
twilio.sid=

resilience4j.retry.instances.sms.max-attempts=2
resilience4j.retry.instances.sms.wait-duration=300ms
resilience4j.retry.instances.sms.enable-exponential-backoff=true
resilience4j.retry.instances.sms.exponential-backoff-multiplier=2

resilience4j.circuitbreaker.instances.sms.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.sms.sliding-window-size=20
resilience4j.circuitbreaker.instances.sms.minimum-number-of-calls=1
resilience4j.circuitbreaker.instances.sms.failure-rate-threshold=5
resilience4j.circuitbreaker.instances.sms.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.sms.permitted-number-of-calls-in-half-open-state=5

resilience4j.ratelimiter.instances.sms.limit-for-period=1
resilience4j.ratelimiter.instances.sms.limit-refresh-period=10s
resilience4j.ratelimiter.instances.sms.timeout-duration=0s
