server.port=8080

spring.application.name=router

spring.main.web-application-type=reactive

spring.cloud.gateway.server.webflux.routes[0].id=session-auth-path
spring.cloud.gateway.server.webflux.routes[0].uri=http://session:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth
spring.cloud.gateway.server.webflux.routes[0].filters[0]=SetPath=/api/v1/auth

spring.cloud.gateway.server.webflux.routes[1].id=session-auth-sub
spring.cloud.gateway.server.webflux.routes[1].uri=http://session:8080
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/auth/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/auth/?(.*),/api/v1/auth/$1

spring.cloud.gateway.server.webflux.routes[2].id=service-message-path
spring.cloud.gateway.server.webflux.routes[2].uri=http://service:8080
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/message
spring.cloud.gateway.server.webflux.routes[2].filters[0]=SetPath=/api/v1/message

spring.cloud.gateway.server.webflux.routes[3].id=service-message-sub
spring.cloud.gateway.server.webflux.routes[3].uri=http://service:8080
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/message/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=RewritePath=/message/?(.*),/api/v1/message/$1
