ALTER TABLE message ALTER COLUMN sender_id DROP NOT NULL;
ALTER TABLE message ADD COLUMN type VARCHAR(16) NOT NULL DEFAULT 'USER';
ALTER TABLE message ADD COLUMN system_event VARCHAR(32);
ALTER TABLE message ADD COLUMN subject_id UUID;
