-- Proper RBAC: split the old per-user "roles" assignment table into
-- role DEFINITIONS (roles) + ASSIGNMENTS (user_roles), with permissions
-- hanging off the definition rather than each user's row.

-- 1. New role-definition table (defined once per role).
CREATE TABLE roles_def (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

-- 2. Carry over the distinct role names that existed as per-user assignments,
--    then ensure the baseline roles exist even on an empty database.
INSERT INTO roles_def (name) SELECT DISTINCT role FROM roles WHERE role IS NOT NULL;
INSERT INTO roles_def (name) VALUES ('USER'), ('ADMIN') ON CONFLICT (name) DO NOTHING;

-- 3. Assignment join table (user ↔ role definition).
CREATE TABLE user_roles (
    user_id UUID   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles_def(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- 4. Migrate existing assignments (old per-user role rows → user_roles).
INSERT INTO user_roles (user_id, role_id)
    SELECT DISTINCT r.user_id, d.id
    FROM roles r JOIN roles_def d ON d.name = r.role
    WHERE r.user_id IS NOT NULL;

-- 5. role_permissions referenced the OLD per-user role ids; rebuild it against
--    the definitions. It carries no data yet (added in V3, none assigned).
DROP TABLE role_permissions;

-- 6. Swap the definition table into place of the old assignment table.
DROP TABLE roles;
DROP SEQUENCE IF EXISTS roles_seq;     -- old @GeneratedValue(AUTO) sequence, now unused
ALTER TABLE roles_def RENAME TO roles;

-- 7. Recreate role_permissions against the role definitions.
CREATE TABLE role_permissions (
    role_id    BIGINT       NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission VARCHAR(255) NOT NULL,
    PRIMARY KEY (role_id, permission)
);

CREATE INDEX idx_role_permissions_role ON role_permissions(role_id);
CREATE INDEX idx_user_roles_role       ON user_roles(role_id);
